### ISSUE TITLE
Query lists doesn't work

### ISSUE THREAD

**Issue by ndias** [pypingou/fedora-active-user#8]
./fedora_active_user.py --email "jaromir.capik@email.cz" --debug   
DEBUG:active-user:Searching mailing lists for email jaromir.capik@email.cz
Last email on mailing list:
DEBUG:active-user:Searching list gmane.linux.redhat.fedora.devel
ERROR:active-user:[Errno socket error] [Errno -2] Name or service not known
Traceback (most recent call last):
  File "./fedora_active_user.py", line 464, in main
    _get_last_email_list(args.email)
  File "./fedora_active_user.py", line 216, in _get_last_email_list
    stream = urllib.urlopen(url)
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno -2] Name or service not known

**Comment by pypingou** [comment]
Ah, with the deprecation of gmane this might need to be adjusted, thanks for the heads-up!

**Comment by sergiomb2** [comment]
yes , --email option doesn't work

**Comment by scfc** [comment]
Work around: ``--nolists`.
